### ISSUE TITLE
Packages: Minor naming mistakes

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#13]
Currently, we've got a minor naming issue concerning the 'Character' model within our Unity packages. Parts of the model, as well as material names, accidentally contain the name 'Figure'.

To fix this, we need to re-export the FBX file(s).

### Tasks

+ [x] Rework the FBX file in Blender
+ [x] Re-export the FBX file properly
+ [x] Check if the packages are fine then
