### ISSUE TITLE
Update of freely available source code

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#15]
As you might have noticed, within this repository, we offer a couple of scripts which are part of Polarith AI for studying major functionalities. Due to the amount of new development work we've done in the last time, we should update them if necessary.

### Tasks

+ [x] Check this public repository for updates
+ [x] Update the freely available source code in this public repository
+ [x] Check the asset packages for updates
+ [x] Update the freely available source code in the asset packages

**Comment by Zireael07** [comment]
Bump. No avoid behavior here at all.

**Comment by martinkirst** [comment]
If you need access to proprietary sources, we can consider adding you to the closed-source repository.
