### ISSUE TITLE
3rd party support: A* Pathfinding Project

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#17]
Many users requested the integration of the popular [__A* Pathfinding Project__](https://www.assetstore.unity3d.com/en/#!/content/87744). So we should do them some good.

### Tasks

+ [ ] Play around with the A* plugins (Free and Pro versions)
+ [ ] Figure out an appropriate integration of the most important features
+ [ ] Write proper adapter(s) based on [`AIMPathfinding`](http://docs.polarith.com/ai/class_polarith_1_1_a_i_1_1_move_1_1_a_i_m_pathfinding.html)
