### ISSUE TITLE
Seek/Flee NavMesh should detect agents outside

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#18]
As our friends at ION LANDS pointed out, at the moment, issues can arise when using [`AIMSeekNavMesh`](http://docs.polarith.com/ai/class_polarith_1_1_a_i_1_1_move_1_1_a_i_m_seek_nav_mesh.html)/[`AIMFleeNavMesh`](http://docs.polarith.com/ai/class_polarith_1_1_a_i_1_1_move_1_1_a_i_m_flee_nav_mesh.html) together with [`AIMUnityPathfinding`](http://docs.polarith.com/ai/class_polarith_1_1_a_i_1_1_move_1_1_a_i_m_unity_pathfinding.html).

Because Unity's pathfinding algorithm often tends to place waypoints near to NavMesh corners, especially for small meshes, the pathfinding and the NavMesh detection stand in their way each other. At a first look, this problem cannot be solved too easily because Unity's API for detecting if an agent is outside of a NavMesh is very rudimentary and expensive as well.

_One possible solution:_ We can utilize Unity's methods for detecting an agent's position relative to a NavMesh. Also, this might be very expensive though. Then, we can invert the magnitudes of the behaviours: When an agent is outside of a NavMesh, an `AIMSeekNavMesh` will become an `AIMFleeNavMesh` and vice versa.

### Tasks

+ [ ] Investigate in different solutions
+ [ ] Evaluate alternate solutions
+ [ ] Implementation of the 'best' solution
+ [ ] Testing
