### ISSUE TITLE
Multi-scene editing

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#21]
It seems that the `AIMSteeringPerceiver` does not support Unity's multi-scene editing at the moment. We should enhance this situation.

### Tasks

+ [ ] Analyze the code base for changes to be made
+ [ ] Discussion with the team and/or the community
+ [ ] Implement a solution
+ [ ] Test the new implementation
+ [ ] Polishing
+ [ ] Final testing
