### ISSUE TITLE
Update to latest Doxygen

### ISSUE THREAD

**Issue by martinkirst** [Polarith/AI#22]
At the moment, we need to stay on Doxygen 1.8.13 due to some HTML changes in newer versions. For example, the left nav tree seems to be incomplete and some margins/paddings, especially on the start page, seem to be broken.

Nevertheless, Dimitri van Heesch made a lot of improvements to Doxygen, especially regarding source code parsing so that the Polarith AI docs would benefit from an update.

### Tasks

+ [ ] Find out all problems using the latest Doxygen version
+ [ ] Fix all issues
  + [ ] Left nav tree incomplete
  + [ ] Broken margins/paddings (on start page)
+ [ ] Review new docs
